name: kthcloud-ci

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to CBH registry
        uses: docker/login-action@v3
        with:
          registry: registry.cloud.cbh.kth.se
          username: ${{ secrets.KTH_REGISTRY_USERNAME }}
          password: ${{ secrets.KTH_REGISTRY_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./clinic_app
          file: ./clinic_app/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ vars.IMAGE }}:latest
            ${{ vars.IMAGE }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ vars.IMAGE }}:buildcache
          cache-to:   type=registry,ref=${{ vars.IMAGE }}:buildcache,mode=max
