# .github/workflows/kthcloud-ci.yml
name: kthcloud-ci

on:
  push: { branches: [ main ] }
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Log in to CBH registry
        uses: docker/login-action@v3
        with:
          registry: registry.cloud.cbh.kth.se
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .            # << repo root (your Dockerfile and src/ are here)
          file: ./Dockerfile    # << Dockerfile is at repo root
          platforms: linux/amd64
          push: true
          tags: |
            ${{ vars.DOCKER_TAG }}:latest
            ${{ vars.DOCKER_TAG }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ vars.DOCKER_TAG }}:buildcache
          cache-to:   type=registry,ref=${{ vars.DOCKER_TAG }}:buildcache,mode=max
